### ISSUE TITLE
Allowing separator characters in usernames

### ISSUE THREAD

**Issue by bhugueney** [nmaro/sorters#1]
Since only lowercase characters are allowed in usernames, it is not possible to use CamelCase for readable composite usernames. I'd have liked to be able to used either '-' or '_' or even '.' as separators.

PS : the error message talks about a number of digits, I think you meant "characters" instead.

**Comment by nmaro** [comment]
Do you think allowing _ would be fair enough?

**Comment by nmaro** [comment]
By the way thanks for writing the first issue for sorters.club! :)

**Comment by bhugueney** [comment]
My pleasure ☺.
'_' would be perfect if you do not mind allowing snakes in your garden : https://en.wikipedia.org/wiki/Snake_case ;)

**Comment by nmaro** [comment]
Done!
