### ISSUE TITLE
Update staart with facebook and google login

### ISSUE THREAD

**Issue by nmaro** [nmaro/sorters#11]
Staart now supports facebook and google authentication. Update to use them.

**Comment by serv** [comment]
Given that FB and Google are increasingly politicizing their company and products, would you be interested in not tying your app to their products? I am concerned what the future holds for these two companies and entrusting them with user authentication seems risky.

I understand that this will decrease the friction for user sign up and login. There's a genuine tradeoff to consider.

**Comment by nmaro** [comment]
Good points. I really think it's defensible to leave this decision to the users, though. One might use fb/google for certain sites and not for others.

**Comment by nmaro** [comment]
Done
