### ISSUE TITLE
Profile avatar

### ISSUE THREAD

**Issue by serv** [nmaro/sorters#16]
Users should be able to upload their own profile avatar.

- Upload a new avatar
  - File size
  - File dimention
  - File formats supported
  - Validate file
- Remove the current avatar
- Replace currently existing avatar with a new one

**Comment by nmaro** [comment]
I'll keep this open, but right now it's already possible to set an avatar using gravatar, so it might be more time-efficient for now to add a link to gravatar with some instructions.

**Comment by serv** [comment]
That make sense.
What do you think about giving the user ability to manage gravatar on this page https://sorters.club/profile

Right below `Your profile is live at /u/`, we can add, `Manage Avatar`, and create a link to Gravatar to manage avatar.

**Comment by nmaro** [comment]
I added an explanation. The Gravatar solution works well.
