### ISSUE TITLE
More detailed profile

### ISSUE THREAD

**Issue by bhugueney** [nmaro/sorters#2]
Could be interesting to add 

- age
- location (country / city)
- gender ;)
- big five scores

**Comment by nmaro** [comment]
Add to that "I have done the self authoring suite"

**Comment by serv** [comment]
I think I'll add another issue related to profile here.

`About you` and `Bio` are similar attributes. It's not obvious to users what they should say differently for either one.

I think you can either concat them and delete one of them, or introduce a *sublabel* for the fields the briefly talk about what you expect the users write in those fields.

**Comment by nmaro** [comment]
Hey @serv thanks for chiming in. The semantic difference is that about will appear in the users page but will be cut. I'd encourage people to write a quick intro in the about section and (if they feel like) a longer bio in the bio section. Sounds legit? Maybe I could add more infos on the form.

**Comment by serv** [comment]
Ah I see what you mean now.

A couple ideas you can play with.

1. Make the textarea smaller for `About you` and larger for `Bio` that hints how much content the user is recommended to give for each area.

2. Use sublabel or description like this below.

![laravel-bootstrap-form-processing](https://user-images.githubusercontent.com/103456/29701932-82497d62-8923-11e7-94d3-87917fef42bb.png)

**Comment by nmaro** [comment]
I'll change the textarea sizes as you suggested. And probably I will use the placeholder text to explain it, since it's an info you only need at the beginning.

**Comment by nmaro** [comment]
Btw this is a good candidate for a first PR ;)

**Comment by serv** [comment]
I would love to help you out with this issue. I'll have some time this weekend :)

**Comment by nmaro** [comment]
Done, thanks @serv for the help
